# -*- coding: utf-8 -*-
{
    'name': 'HR Store',
    'description': "Summer Work",
    'author': "Team One",
    'version': '2.0.2',
    'category': 'Uncategorized',
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/admin.xml',
        'views/login.xml',
        'views/sign_up.xml',
        'views/template.xml',
        'views/home.xml',
        'views/products.xml',
        'views/customer_service.xml',
        'views/product_details.xml',
        'views/supplier_addProduct.xml',
        'views/supplier_changeStatus.xml',
        'views/supplier_orderlist.xml',
        'views/supplier_publishedProduct.xml',
        'views/supplier_updateInfo.xml',
        'views/supplier_updatePublishedProduct.xml',
        'views/customer_info.xml',
        'views/customer_modifyInfo.xml',
        'views/customer_order.xml',
        'views/customer_comment.xml',
        'views/confirm_order.xml',
        'views/add_address.xml',
        'views/pay_order.xml',
        'views/forum.xml'
    ],

    'depends': ['base', 'website'],
}
